replicaCount: 1

image:
  repository: dgraziotin/nginx-webdav-nononsense
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

storage:
  pvc: false
  host: true
  path: /var/podnat-state
  class: ""
  size: "1G"
