apiVersion: v1
kind: Service
metadata:
  name: {{ include "podnat-state-store.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "podnat-state-store.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "podnat-state-store.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "podnat-state-store.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "podnat-state-store.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "podnat-state-store.fullname" . }}
