apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "podnat-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "podnat-controller.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "podnat-controller.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "podnat-controller.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podnat-controller.serviceAccountName" . }}
      hostNetwork: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: []
        {{- $arg_list := uniq ( append .Values.extra_args "-logtostderr" ) }}
        args: {{ $arg_list }}
        ports:
          - containerPort: 8484
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8484
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

