name: Docker Image Dev CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set version
      id: version
      run: |
        chart_file=build/package/helm/podnat-controller/Chart.yaml
        chart_release_version=$(awk -F: '/^version:/ {gsub(/ /, "");print $2}' $chart_file)
        sha_short=$(git rev-parse --short "${{ github.event.pull_request.head.sha }}")
        echo "version=${chart_release_version}-dev-${sha_short}" >> $GITHUB_OUTPUT

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        file: build/package/Dockerfile
        push: true
        tags: gutmensch/podnat-controller:${{ steps.version.outputs.version }}

